# Profil DEV
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO
    com.modeltech.datamasteryhub: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/modeltech-backend.log