# Profil STAGING (VPS Dokploy)
spring:
  config:
    activate:
      on-profile: staging
  jpa:
    show-sql: true

logging:
  level:
    ROOT: INFO
    bank.cbao.smartbilling: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/modeltech-backend.log

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  masterclass:
    meet-link: ${MASTERCLASS_MEET_LINK:https://meet.google.com/vbh-nodg-qwe}
