# Profil STAGING (VPS Dokploy)
spring:
  config:
    activate:
      on-profile: staging
  jpa:
    show-sql: false

logging:
  level:
    com.modeltech: INFO
    org.springframework.security: INFO

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
