

ALTER TABLE alumni ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE alumni ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE alumni ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE alumni ADD COLUMN IF NOT EXISTS deleted_by TEXT;


ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS deleted_by TEXT;


ALTER TABLE project_members ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE project_members ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE project_members ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE project_members ADD COLUMN IF NOT EXISTS deleted_by TEXT;


ALTER TABLE project_screenshots ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE project_screenshots ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE project_screenshots ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE project_screenshots ADD COLUMN IF NOT EXISTS deleted_by TEXT;